### ISSUE TITLE
JDK 9+ Compatability with Project Jigsaw & module-info.class

### ISSUE THREAD

**Issue by concision** [argparse4j/argparse4j#123] opened 2020-09-22 06:21 UTC
With the release of JDK9, [Project Jigsaw](https://openjdk.java.net/projects/jigsaw/) was introduced into the Java ecosystem.  The most prominent advantage for adopting these (relatively) new features is for modularization of dependencies. The CLI tool [`jlink`](https://openjdk.java.net/jeps/282) was introduced into the JDK that allows building a custom minimal JRE using only the necessary native Java modules that a module requires.

Currently, this project does not have a `module-info.java` that explicitly states all of its dependencies and namespace. This causes some incompatibility issues when developing a project with argparse4j, since automatic module names are generated for it (i.e. `argparse4j`, and not `net.sourceforge.argparse4j`). Is there any chance that JDK/JRE 9+ modularization can be supported in this project?

Without it, the Maven compiler outputs the following:
```
[WARNING] Can't extract module name from classes: C:\[REDACTED]\target\classes
[WARNING] ********************************************************************************************************************************************
[WARNING] * Required filename-based automodules detected: [argparse4j-0.8.1.jar]. Please don't publish this project to a public artifact repository! *
[WARNING] ********************************************************************************************************************************************
```

A quick note: adding a `module-info.java` is generally backwards compatible; a Maven configuration can be used to compile the `module-info.java` for Java 9, but retain lower Java versions for the rest of the classes (I have an example in [one of my repositories](https://github.com/concision/unpacker-toolchain/blob/d577d64d2cc2ada3e8125b12a87502bb4b01c8dc/api/pom.xml#L32-L81))

**Comment by jstuyts** [comment] 2020-09-27 20:03
I don't see a problem with that. As I do not know how argparse4j is used, I also do not know which classes are accessed by client code. I guess this means I have to make all packages public. Later major revisions can then only expose the classes that are part of the public interface.

The biggest obstacle at this moment is having the time to add this to the build, and to make a new release.

**Comment by concision** [comment] 2020-09-27 20:28
Exposing all packages/classes publicly should be fine as a minor change - making a major change that only exposes the public API would be ideal, but I understand the hesitance to make a breaking change. I would very much like to see this support, as it would stabilize JDK9+ support for several projects I use that are based on this library.

If I authored a pull request for this issue, would you have the time to be able to review it and potentially merge? I suspect it should not take _too_ long, but I can understand these things can vary drastically in implementation time.

Thank you for your time and work on this project!

**Comment by jstuyts** [comment] 2020-09-27 20:31
A pull request is always welcome. If you submit one I will review and merge it.

**Comment by concision** [comment] 2020-09-27 20:40
Sounds good - I will spend some time making a pull request within the next couple days.

**Comment by concision** [comment] 2020-09-28 14:07
The pull request for this is over at #124. 

I did not realize my experimental changes (with copious amounts of force pushing) would be logged in this issue - lesson learned.

**Comment by jstuyts** [comment] 2020-10-01 15:42
I made the build a bit faster by minimizing what is compiled using Java 9. It looked good, so I merged it. Thanks for your work.

**Comment by concision** [comment] 2020-10-01 19:16
One caveat with that changes is that the validity of `requires` statements in the `module-info.java`s will not be properly validated against the sources, since the only source in the `jdk9-compile` is `module-info.java`. For example, removing the following lines in the module `argparse4j-hadoop` will _still_ compile successfully, but will generate a jar that does not have all its modules specified correctly and could lead to errors for developers.

https://github.com/argparse4j/argparse4j/blob/783f8ac3754f732797bcf0470fc7ad9453f04640/extensions/hadoop/src/main/java/module-info.java#L3-L4

Please keep that in mind when adding any other dependency that you will need to _ensure_ your `module-info.java` explicitly includes the relevant dependencies before pushing to Maven central, because the Maven build _will not_ catch this error by only including `module-info.java` for compilation.

We can simplify the build times using a multi-release JAR if necessary, the setup just becomes more complicated (but is _not_ hacky). The project builds from scratch in under 10 seconds on my setup, so I did not think the build times were too excessive with the dual compilation. I think a big slowdown in the CI/CD configuration is uncached Maven dependencies, which we could also resolve (see https://docs.travis-ci.com/user/caching/) in another PR.

<hr>

If this PR is all good, I can create a new PR simplifying the build setup to only require JDK 9+ (which is needed anyways) rather than JDK6/7 as well, which should alleviate developer headaches.

**Comment by jstuyts** [comment] 2020-10-01 19:56
Javadoc was broken in the Maven build because of the changes for Java 9. It is working again now.

I will keep updating the dependencies in `module-info.java` files in mind when making changes.

I will look at caching on Travis CI.

Maybe switching to Gradle is a better investment than messing around with Maven.

I am closing this issue now, as the currently built JAR files look good. Please reopen if you find another issue related to JDK 9 support.

**Closed** 2020-10-01 19:57 UTC

**Comment by jstuyts** [comment] 2021-02-25 21:24
@concision Implementing this moved the problem you had to the Hadoop extension, because (the version argparse4j uses and later versions of) `hadoop-common` do not have an explicit module name.

I hope to release a new version in the near future, but the Maven warning is blocking.

The problem is solved by not including module information in the Hadoop extension. Do you use this extension? If not, I am going to remove module information for it. If it introduces problems for someone else, I guess I have to tell them to nag the Hadoop team to pick a module name.

**Comment by concision** [comment] 2021-02-26 02:05
As you suggested, we should probably opt to remove the module information from the Hadoop extension since it requires upstream support from the Hadoop team. I personally do not use the extension. 

The vexing part of trying to integrate module information for a dependency is trying to PR _all_ upstream transitive dependencies, which is no fun. In this PR, I was trying to be uniform with applying the module information to the entire project, but I must have missed that warning/discrepancy.

**Comment by jstuyts** [comment] 2021-02-26 12:08
Thanks for your answer. I will remove module information from the Hadoop extension.
