### ISSUE TITLE
Path relative to a parent directory

### ISSUE THREAD

**Issue by replicant-tech** [argparse4j/argparse4j#110] opened 2018-03-02 14:37 UTC
Example:
  `parser.addArgument("file").type(Arguments.fileType().verifyExists());`
  `./<my_program> ../<file_path>`

When path to a file is relative to a parent directory, eg. "../<file_path> ArgParse4j is not able to find the file. 
I consider that expected behaviour would be parser to find the file relative to the directory where program is being run from. In Java that directory is available from JVM as `System.getProperty("user.dir")`

**Comment by jstuyts** [comment] 2018-03-03 19:23
@replicant-tech: Can you provide more information, because I cannot reproduce this with the code in `master`? Please specify your operating system, Java version and argparse4j version. Thanks in advance.

**Comment by replicant-tech** [comment] 2018-03-05 13:35
@jstuyts I have tried the latest 0.8.1 argparse4j version on Ubuntu 16.04. It doesn't work on Amazon Linux as well

**Comment by replicant-tech** [comment] 2018-03-05 13:39
My example is a little misleading, it is actually `subparser.addArgument("file")`

**Comment by jstuyts** [comment] 2018-03-07 21:15
I tried it with Ubuntu 16.04.4, OpenJDK 1.8.0_151 and the `master` branch, but I cannot reproduce the issue. Which filesystem do you use? Are there any symlinks involved?

Can you check out branch `issue-110-path-relative-to-parent`, and run `runIssue110Tests.sh`? Please copy the output of that shell script starting from `### startdir ###`. Thanks.

**Comment by replicant-tech** [comment] 2018-03-12 18:43
Thank you, your test are working as expected even on my setup. I will try modifying the test to recreate the issue.

**Comment by jstuyts** [comment] 2018-04-03 09:15
No reproduction scenario was given and 3 weeks have past. Closing the issue.

**Closed by jstuyts** 2018-04-03 09:15 UTC
Labels: bug
